---
abstract: 'RT-Extension-Assets-Import-CSV Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Assets-Import-CSV
no_index:
  directory:
    - inc
requires:
  RT::Extension::Assets: 0
  Text::CSV_XS: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.4'
x_module_install_rtx_version: '0.36'
x_requires_rt: 4.2.1
x_requires_rt_plugins:
  - RT::Extension::Assets
